# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(764, 617)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_textEdit = QtWidgets.QPlainTextEdit(Form)
        self.input_textEdit.setTabStopWidth(79)
        self.input_textEdit.setObjectName("input_textEdit")
        self.horizontalLayout.addWidget(self.input_textEdit)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cifa_btn = QtWidgets.QPushButton(Form)
        self.cifa_btn.setObjectName("cifa_btn")
        self.verticalLayout_2.addWidget(self.cifa_btn)
        self.yufa_btn = QtWidgets.QPushButton(Form)
        self.yufa_btn.setEnabled(False)
        self.yufa_btn.setObjectName("yufa_btn")
        self.verticalLayout_2.addWidget(self.yufa_btn)
        self.after_btn = QtWidgets.QPushButton(Form)
        self.after_btn.setEnabled(False)
        self.after_btn.setObjectName("after_btn")
        self.verticalLayout_2.addWidget(self.after_btn)
        self.front_btn = QtWidgets.QPushButton(Form)
        self.front_btn.setEnabled(False)
        self.front_btn.setObjectName("front_btn")
        self.verticalLayout_2.addWidget(self.front_btn)
        self.clearReuslt_btn = QtWidgets.QPushButton(Form)
        self.clearReuslt_btn.setObjectName("clearReuslt_btn")
        self.verticalLayout_2.addWidget(self.clearReuslt_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.show_textBrowser = QtWidgets.QTextBrowser(Form)
        self.show_textBrowser.setObjectName("show_textBrowser")
        self.horizontalLayout.addWidget(self.show_textBrowser)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cifa_btn.setText(_translate("Form", "词法分析"))
        self.yufa_btn.setText(_translate("Form", "语法分析"))
        self.after_btn.setText(_translate("Form", "后缀表达式求值"))
        self.front_btn.setText(_translate("Form", "前缀表达式求值"))
        self.clearReuslt_btn.setText(_translate("Form", "清空输出结果"))
